### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by Fleurrr** [Tobias-Fischer/ensemble-event-vpr#2]
Thanks for your your wonderful work！
Can you share the data select from DDD17 if convenient?

**Comment by Tobias-Fischer** [comment]
Hi,

You can get the DDD17 dataset from [here](https://docs.google.com/document/u/1/d/1HM0CSmjO8nOpUeTvmPjopcBcVCk7KXvLUuiZFS6TWSg/pub).

I used the following sets of traverses:
Set 1: run4/rec1487779465; section with timestamps in range (1487779570.387452840805, 1487780606.381024837494) and run4/rec1487782014; section with timestamps in range (1487782119.368249893188, 1487783131.372107982635)
Set 2: run3/rec1487350455; section with timestamps in range (1487350587.121543884277, 1487351006.119336843491) and run3/rec1487417411; section with timestamps in range (1487417732.687336921692, 1487418001.687238931656). I also excluded the following sections with route deviations: 1487350725.125939 to 1487350750.1558042 and 1487417835.9302948 to 1487417857.282901

I excluded the following times where the car was at standstill:
```python
{
'run4/rec1487779465': [(1487779618.368702, 1487779621.37651), (1487779639.376494, 1487779640.376642), (1487780083.395329, 1487780086.385159), (1487780108.383698, 1487780152.380815), (1487780199.38108, 1487780201.3682559), (1487780559.395974, 1487780569.386682)],
'run4/rec1487782014': [(1487782108.381295, 1487782112.3818989), (1487782164.365999, 1487782184.364292), (1487782626.353911, 1487782628.363847), (1487782658.3817198, 1487782719.3797278), (1487782757.3551009, 1487782760.354826), (1487783082.3637109, 1487783090.372325)],
'run3/rec1487350455': [(1487350457.109958, 1487350461.1112099), (1487350523.125653, 1487350545.124213), (1487351629.128463, 1487351629.128463), (1487351675.122474, 1487351676.1218119), (1487351685.110925, 1487351686.121429), (1487351712.121937, 1487351717.117389)],
'run3/rec1487417411': [(1487417422.686799, 1487417429.675303), (1487417466.6843328, 1487417466.6843328), (1487417537.6839619, 1487417544.6756399)],
}
```

I used the associated GPS data to find correspondences between the query and reference traverses.

Otherwise I used the same code as in this repository.

**Comment by Fleurrr** [comment]
Thank you very much!
