### ISSUE TITLE
About training from scratch

### ISSUE THREAD

**Issue by lannester666** [Tobias-Fischer/ensemble-event-vpr#4]
Hi, thank you for sharing your great work! We want to train the model from scratch and see how it works, however, we find that you directly share the trained checkpoints without the training code. Can you share this part so we can learn about your work more in detail?

**Comment by Tobias-Fischer** [comment]
Hi @lannester666, we use the pre-trained network from https://github.com/uzh-rpg/netvlad_tf_open. If you want to train your own network in Python with PyTorch, please see for example our https://github.com/QVPR/Patch-NetVLAD repository (but please note you would need to change the code here to work with this repository rather than with the netvlad_tf_open repo which is based on tensorflow.

**Comment by lannester666** [comment]
Thank you for your answer!^_^
